### PR TITLE
feat: add github hooks pre-commit

### PR DESCRIPTION
**Pull request by apollo-pablo**
> Problem

Sometime when we commit later it fail for fmt or clippy, lets fix this .)

> Tasks

- [x] Add github action hooks pre-commit to check fmt, clippy and tests.

### CODE REVIEW

**Comment by apollo-pablo** [comment]
@apollo-bobby I created the bash using `sh`, but it can be `bash`. Dont know if plays well with mac

**Comment by apollo-bobby** [comment]
Does the script print error messages or only your `echo`s?

**Comment by apollo-pablo** [comment]
> Does the script print error messages or only your `echo`s?

If fail echo an error message if fmt/clippy/test fail (no need to show specific errors) and exit with 1. If success echo a message with OK and exit 0.

**Comment by apollo-bobby** [comment]
> no need to show specific errors

I disagree, that's exactly what I would want if my pre-commit failed. So I can immediately fix the issue and re-commit rather than running clippy (or whatever) again to see what went wrong.

**Comment by apollo-pablo** [comment]
> > no need to show specific errors
> 
> I disagree, that's exactly what I would want if my pre-commit failed. So I can immediately fix the issue and re-commit rather than running clippy (or whatever) again to see what went wrong.

But this a pre-commit hook to **avoid** making a commit with errors. Suppose the following scenario where linting fail and returns 50 errors, the developer is not going to **commit** every time to fix one by one the errors, it will run **cargo clippy** or add to rust analyzer on Save the clippy command. If 4 test fails, it will run **cargo test**. Remember this is execute previous to commit, so it will not allow you to commit until you fix all errors.

**Comment by apollo-bobby** [comment]
> > > no need to show specific errors
> > 
> > 
> > I disagree, that's exactly what I would want if my pre-commit failed. So I can immediately fix the issue and re-commit rather than running clippy (or whatever) again to see what went wrong.
> 
> But this a pre-commit hook to **avoid** making a commit with errors. Suppose the following scenario where linting fail and returns 50 errors, the developer is not going to **commit** every time to fix one by one the errors, it will run **cargo clippy** or add to rust analyzer on Save the clippy command. If 4 test fails, it will run **cargo test**. Remember this is execute previous to commit, so it will not allow you to commit until you fix all errors.

Yes, I know how pre-commit hooks work thank you :) Maybe we use them differently but in my experience I don't get a thousand errors on pre-commit, but rather maybe 1 or 2 (usually something silly), in which case it's very convenient to see the error immediately. Then, I fix it quickly, add the file, commit again and hope that it doesn't fail again.

**Comment by apollo-bobby** [comment]
Add a check for an environment variable like `PRECOMMIT_VERBOSE_ERRORS` or something and the user can choose.

**Pull request merged**
